apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: graphql-gateway
    app.kubernetes.io/part-of: capstone
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: graphql-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
