apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/part-of: capstone
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
