apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: capstone
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: order-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
